/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'stewy' at '3/21/17 9:02 PM' with Gradle 2.10
 *
 * @author stewy, @date 3/21/17 9:02 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
